name: Feature Request
description: Suggest a change or new feature
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Please provide all fields with the required (*) icon
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I am using the latest version as listed [here](https://github.com/WilliamSchack/Spotify-Downloader/releases/latest)
          required: true
        - label: I have verified that this feature does not already exist
          required: true
  - type: textarea
    id: description
    attributes:
      label: Provide a description of the feature or change
      description: Describe what the problem is and why a change/new feature should be implemented
      placeholder: |
        For example: "This setting makes it hard to ..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Propose a solution
      description: Describe the best way you would solve the problem, or a description of what you would want to happen
      placeholder: Propose a solution or provide a description of your ideal outcome
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Complete Log
      description: |
        If the request is a change to a current feature, please perform the current actions in the app and provide the logs.
        You can find your most recent log at the file location (%temp%/SpotifyDownloader/Log.log).
        Please copy all the text and input it below. It should start like the following:
      placeholder: |
        10-08-2025 00:44:04 |   Info   | 10 | SpotifyDownloader.cpp | SpotifyDownloader | RUNNING VERSION "1.10.0"
        10-08-2025 00:44:05 |   Info   | 185 | Config.cpp | LoadSettings | Settings Successfully Loaded QJsonObject({})
        10-08-2025 00:44:05 |   Info   | 66 | SpotifyDownloader.cpp | SetupDownloaderThread | Successfully Setup Playlist Worker Thread
        10-08-2025 00:44:05 |   Info   | 157 | SpotifyDownloader.cpp | CheckForUpdate | Latest Version: "v1.10.0" | Update Available: false
        10-08-2025 00:44:05 |   Info   | 37 | SpotifyDownloader.cpp | SpotifyDownloader | Successfully Initialised
        <continues from here>
      render: shell
